import { z } from "zod";

const recordSchema = z.record(z.unknown());
const positionSchema = z.object({ x: z.number(), y: z.number() });
const viewportSchema = z.object({ x: z.number(), y: z.number(), k: z.number() });
const nodeTypeSchema = z.enum(["image", "text", "script", "comfyui", "video", "audio"]);
const generationModeSchema = z.enum(["text", "image", "video", "audio"]);

export const toolNames = [
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "canvas_retry_node",
    "canvas_execute_group",
    "canvas_group_nodes",
    "canvas_ungroup_nodes",
    "canvas_image_edit",
    "canvas_image_quick_command",
    "canvas_image_process",
    "canvas_grid_storyboard",
    "canvas_video_analyze",
    "canvas_video_trim",
    "canvas_video_compose",
    "canvas_save_template",
    "canvas_insert_template",
    "canvas_comfyui_list_workflows",
    "canvas_comfyui_get_workflow",
    "canvas_comfyui_set_workflow",
] as const;
export type ToolName = (typeof toolNames)[number];

export const canvasOpSchema = z.discriminatedUnion("type", [
    z.object({ type: z.literal("add_node"), nodeType: nodeTypeSchema.optional(), id: z.string().optional(), title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), position: positionSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("update_node"), id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }).passthrough(),
    z.object({ type: z.literal("delete_node"), id: z.string().optional(), ids: z.array(z.string()).optional() }).passthrough(),
    z.object({ type: z.literal("delete_connections"), id: z.string().optional(), ids: z.array(z.string()).optional(), all: z.boolean().optional() }).passthrough(),
    z.object({ type: z.literal("connect_nodes"), id: z.string().optional(), fromNodeId: z.string(), toNodeId: z.string() }).passthrough(),
    z.object({ type: z.literal("set_viewport"), viewport: viewportSchema }).passthrough(),
    z.object({ type: z.literal("select_nodes"), ids: z.array(z.string()) }).passthrough(),
    z.object({ type: z.literal("run_generation"), nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }).passthrough(),
]);

const textNodeSchema = z.object({
    text: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    width: z.number().optional(),
    height: z.number().optional(),
});

const generationOptionsSchema = z.object({
    model: z.string().optional(),
    size: z.string().optional(),
    quality: z.string().optional(),
    resolution: z.string().optional(),
    count: z.number().optional(),
    seconds: z.string().optional(),
    vquality: z.string().optional(),
    generateAudio: z.string().optional(),
    watermark: z.string().optional(),
    audioVoice: z.string().optional(),
    audioFormat: z.string().optional(),
    audioSpeed: z.string().optional(),
    audioInstructions: z.string().optional(),
});

const generationFlowSchema = z.object({
    prompt: z.string(),
    title: z.string().optional(),
    x: z.number().optional(),
    y: z.number().optional(),
    referenceNodeIds: z.array(z.string()).optional(),
});

export const toolInputSchemas = {
    canvas_get_state: z.object({}).passthrough(),
    canvas_get_selection: z.object({}).passthrough(),
    canvas_export_snapshot: z.object({}).passthrough(),
    canvas_apply_ops: z.object({ ops: z.array(canvasOpSchema) }),
    canvas_create_node: z.object({ nodeType: nodeTypeSchema, title: z.string().optional(), x: z.number().optional(), y: z.number().optional(), width: z.number().optional(), height: z.number().optional(), metadata: recordSchema.optional() }),
    canvas_create_text_node: z.object({ text: z.string().optional(), x: z.number().optional(), y: z.number().optional(), title: z.string().optional(), width: z.number().optional(), height: z.number().optional() }),
    canvas_create_text_nodes: z.object({ items: z.array(textNodeSchema).min(1), x: z.number().optional(), y: z.number().optional(), gap: z.number().optional(), direction: z.enum(["row", "column"]).optional() }),
    canvas_create_image_prompt_flow: z.object({ prompt: z.string(), x: z.number().optional(), y: z.number().optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_create_generation_flow: generationFlowSchema.extend({ mode: generationModeSchema.optional(), autoRun: z.boolean().optional() }).merge(generationOptionsSchema),
    canvas_generate_text: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_image: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_video: generationFlowSchema.merge(generationOptionsSchema),
    canvas_generate_audio: generationFlowSchema.merge(generationOptionsSchema),
    canvas_update_node: z.object({ id: z.string(), patch: recordSchema.optional(), metadata: recordSchema.optional() }),
    canvas_update_node_text: z.object({ id: z.string(), text: z.string(), title: z.string().optional() }),
    canvas_move_nodes: z.object({ items: z.array(z.object({ id: z.string(), x: z.number().optional(), y: z.number().optional(), dx: z.number().optional(), dy: z.number().optional() })).min(1) }),
    canvas_resize_node: z.object({ id: z.string(), width: z.number(), height: z.number(), freeResize: z.boolean().optional() }),
    canvas_delete_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_connect_nodes: z.object({ connections: z.array(z.object({ fromNodeId: z.string(), toNodeId: z.string() })).min(1) }),
    canvas_select_nodes: z.object({ ids: z.array(z.string()) }),
    canvas_set_viewport: z.object({ viewport: viewportSchema }),
    canvas_run_generation: z.object({ nodeId: z.string(), mode: generationModeSchema.optional(), prompt: z.string().optional() }),
    canvas_retry_node: z.object({ id: z.string() }),
    canvas_execute_group: z.object({ id: z.string() }),
    canvas_group_nodes: z.object({ ids: z.array(z.string()).min(1), variant: z.enum(["normal", "storyboard"]).optional() }),
    canvas_ungroup_nodes: z.object({ ids: z.array(z.string()).min(1) }),
    canvas_image_edit: z.object({ id: z.string(), action: z.enum(["angle", "outpaint", "lighting", "cutout", "panorama720"]), params: recordSchema.optional() }),
    canvas_image_quick_command: z.object({ id: z.string(), commandId: z.enum(["lens-focus", "focus-edit", "cinematic-lighting", "character-turnaround", "extrapolate-forward", "extrapolate-backward"]) }),
    canvas_image_process: z.object({ id: z.string(), action: z.enum(["crop", "split", "upscale"]), params: recordSchema.optional() }),
    canvas_grid_storyboard: z.object({ id: z.string(), commandId: z.enum(["four-grid", "nine-grid", "twentyfive-grid"]) }),
    canvas_video_analyze: z.object({ id: z.string() }),
    canvas_video_trim: z.object({ id: z.string(), start: z.number(), end: z.number() }),
    canvas_video_compose: z.object({ id: z.string(), clips: z.array(z.object({ nodeId: z.string(), start: z.number().optional(), end: z.number().optional() })).optional() }),
    canvas_save_template: z.object({ ids: z.array(z.string()).min(1), name: z.string() }),
    canvas_insert_template: z.object({ templateId: z.string().optional(), name: z.string().optional() }),
    canvas_comfyui_list_workflows: z.object({}).passthrough(),
    canvas_comfyui_get_workflow: z.object({ workflowId: z.string().min(1) }),
    canvas_comfyui_set_workflow: z.object({ nodeId: z.string().min(1), workflowId: z.string().min(1), values: z.record(z.unknown()).optional() }),
} satisfies Record<ToolName, z.AnyZodObject>;

export const toolDescriptions: Record<ToolName, string> = {
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布。ops 支持 add_node、update_node、delete_node、delete_connections、connect_nodes、set_viewport、select_nodes、run_generation。",
    canvas_create_node: "创建任意类型节点：text、image、comfyui、video、audio、script。适合创建占位图、媒体占位、ComfyUI 工作流或自定义 metadata 节点。创建脚本节点：nodeType=\"script\"，并把剧本正文写入 metadata.scriptBody。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建普通文本节点，适合生成标题、段落、说明等内容块；剧本/脚本请用 canvas_create_node 创建脚本节点。",
    canvas_create_image_prompt_flow: "创建提示词文本节点和图片目标节点，并自动连线，可选择立即触发生图。",
    canvas_create_generation_flow: "创建通用生成流程：提示词文本节点、对应类型的生成目标节点和参考节点连线，可用于文案、生图、视频或音频。",
    canvas_generate_text: "创建通用文本生成流程并立即触发生成。",
    canvas_generate_image: "创建通用图片生成流程并立即触发生成。可选 model 指定模型、resolution（1k/2k/4k）指定分辨率档。",
    canvas_generate_video: "创建通用视频生成流程并立即触发生成。可选 model 指定模型、vquality（480p/720p/1080p）指定分辨率。",
    canvas_generate_audio: "创建通用音频生成流程并立即触发生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点，支持绝对坐标或 dx/dy 偏移。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定的文本、图片、视频或音频节点生成。",
    canvas_retry_node: "沿用上次参数重跑指定节点。",
    canvas_execute_group: "整组拓扑重跑，传入组内任意节点 id。",
    canvas_group_nodes: "把多个节点打组，variant 可选 normal 或 storyboard（分镜组）。",
    canvas_ungroup_nodes: "解散指定节点所在的组。",
    canvas_image_edit: "图片节点 AI 编辑：angle 多角度（params: horizontalAngle/pitchAngle/cameraDistance/wideAngle）、outpaint 扩图（params.ratioId 如 16:9）、lighting 打光（params.direction/color/intensity）、cutout 抠图、panorama720 720° 全景。",
    canvas_image_quick_command: "图片节点快捷指令：lens-focus 镜头聚焦、focus-edit 焦点编辑、cinematic-lighting 电影级光影矫正、character-turnaround 角色三视图、extrapolate-forward 画面推演（+3 秒后）、extrapolate-backward 画面推演（-5 秒前）。",
    canvas_image_process: "图片节点本地处理：crop 裁剪（params: x/y/width/height）、split 宫格切分（params: rows/columns）、upscale 高清放大（params: targetLongEdge 1024/2048/4096、algorithm）。",
    canvas_grid_storyboard: "图片节点快捷分镜：four-grid 四宫格、nine-grid 九宫格、twentyfive-grid 25 宫格连贯分镜。",
    canvas_video_analyze: "解析视频节点：抽帧并生成分镜表脚本节点。",
    canvas_video_trim: "按入点/出点裁剪视频节点，导出片段为新节点。",
    canvas_video_compose: "视频合成：clips 指定片段（nodeId + 可选 start/end 出入点），不传 clips 则按现有连线合成。",
    canvas_save_template: "把指定节点组（含连线）保存为账号级画布模板。",
    canvas_insert_template: "把已保存的画布模板插入当前画布，按 templateId 或 name 定位。",
    canvas_comfyui_list_workflows: "列出当前可用的 ComfyUI 工作流（含 id/名称/能力 capability/是否默认），用于选择工作流。判断规则：按用户任务匹配 capability（如 放大/重绘/转绘/生成），匹配不到时使用默认工作流。",
    canvas_comfyui_get_workflow: "读取 ComfyUI 工作流详情（字段定义/类型/默认值），生成前用 canvas_comfyui_set_workflow 把字段值写入节点。",
    canvas_comfyui_set_workflow: "为 ComfyUI 节点指定工作流并写入字段值（values 为字段 id 到值的映射）。创建 ComfyUI 节点后必须先调用本工具设置工作流再运行。",
};
